---
title:    "Version 2.3.0 Release Notes"
subtitle: "Release Date: 9 Jul 2019"
keywords: "release notes"
menu:
  main:
    name:       "V2.3.0 Release Notes"
    parent:     "release-notes-2.3"
    identifier: "release-notes-2.3.0"
    weight:     900
---
{{< comment >}}<!-- [TODO-POST-REVIEW] Remove the internal-release-note
  "reviewer" param for each reviewed note. => (10.7.19) DONE for v2.3.0. -->
<!-- TODO: At the end, check all section cross-references notes to ensure
  they're relevant to the final release notes for this version. -->
{{< /comment >}}

This document outlines the main additions and changes to the Iguazio MLOps Platform ("the platform") in version 2.3.0, and known issues in this version.

{{< techpreview note="1" >}}

{{< comment >}}<!-- [IntInfo] (sharonl) The RNs don't include beta features. -->
{{< beta note="1" >}}
{{< /comment >}}

{{< internal-release-note id="internal-release-jira-n-confluence-links" >}}
**V2.3.0 RNs DOC Task:** {{< jira ig="12318" >}}
<br/>
**[Release Index](http://confluence.iguazeng.com:8090/display/RM/Release+Index) (Confluence):** &mdash; [2.3.0](http://confluence.iguazeng.com:8090/display/RM/Release+Index#ReleaseIndex-2.3.0)
<br/>
**R&D Jira Dashboards:** [2.3.0 Status](https://jira.iguazeng.com/secure/Dashboard.jspa?selectPageId=11209) ; [2.3.0 Program](https://jira.iguazeng.com/secure/Dashboard.jspa?selectPageId=11202)
<br/>
**V2.3.0 Requirements &mdash; Jira:** [All](https://jira.iguazeng.com/issues/?jql=project%20=%20ig%20AND%20(%22Target%20Version%22%20in%20(2.3.0)%20OR%20fixVersion%20in%20(2.3.0)%20OR%20affectedVersion%20in%20(2.3.0))%20AND%20issuetype%20=%20Requirement); [Tested](https://jira.iguazeng.com/issues/?jql=project%20=%20ig%20AND%20(%22Target%20Version%22%20in%20(2.3.0)%20OR%20fixVersion%20in%20(2.3.0)%20OR%20affectedVersion%20in%20(2.3.0))%20AND%20issuetype%20=%20Requirement%20AND%20status%20=%20Tested); [Done](https://jira.iguazeng.com/issues/?jql=project%20=%20ig%20AND%20(%22Target%20Version%22%20in%20(2.3.0)%20OR%20fixVersion%20in%20(2.3.0)%20OR%20affectedVersion%20in%20(2.3.0))%20AND%20issuetype%20=%20Requirement%20AND%20status%20=%20Done); [Open](https://jira.iguazeng.com/issues/?jql=project%20=%20ig%20AND%20(%22Target%20Version%22%20in%20(2.3.0)%20OR%20fixVersion%20in%20(2.3.0)%20OR%20affectedVersion%20in%20(2.3.0))%20AND%20issuetype%20=%20Requirement%20AND%20status%20in%20(Done,%20Tested,%20Canceled,%20Cancelled))
<br/>
**V2.3.0 release-notes tickets:** [Jira query](https://jira.iguazeng.com/issues/?jql=project%20=%20ig%20AND%20(%22External%20Release%20Note%22%20in%20(Required,%20Candidate)%20AND%20NOT%20labels%20in%20(RN-future-version)%20OR%20%22External%20Release%20Note%22%20=%20Done-Known-Issues%20OR%20labels%20in%20(RN-2.3.0,%20RN-2.3.0-fixes,%20RN-2.3.0-known-issues,%20RN-2.3.0-TechPreview))%20AND%20NOT%20labels%20in%20(RN-2.3-excluded-fixes,%20RN-2.3-excluded-known-issues))
<br/>
**Issues intentionally excluded from the v2.3.0 RNs:** [Jira query](https://jira.iguazeng.com/issues/?jql=labels%20in%20(RN-2.3-excluded-fixes,%20RN-2.3-excluded-known-issues))
{{< /internal-release-note >}}

{{< internal-rn-heading.inline >}}
{{- if eq (getenv "IGZ_BUILD_INTERNAL") "true" -}}
<!-- //////////////////////////////////////// -->
<h2 style="color:BlueViolet;" id="internal-open-issues-n-questions">[INTERNAL] OPEN ISSUES &amp; QUESTIONS</h2>
<!-- [InfraInfo] Trying to use the rn-heading shortcode within this inline
  shortcode produces this error: "inline shortcodes do not support nesting" -->
{{- end -}}
{{< /internal-rn-heading.inline >}}

<!-- V2.3.0 Fixes Pending Verification -->
{{< internal-release-note title="V2.3.0 Fixes Pending Verification" id="current-release-fixes-pending-verification" >}}
The following bugs were fixed in v2.3.0 but are pending verification of the fix by QA/others in order to move the related release notes from the **Known Issues** section to the **Fixes** section or remove known issues added only in the v2.3.0 release notes:

- <a id="Q-ig-11717"></a>[The dashboard might occasionally display an unreachable server or site error, specifically after an expired browser session, which can be resolved only by refreshing the browser page](#ki-ui-server-or-site-cant-be-reached) &mdash; **Bug {{< jira ig="11717" >}}**.
  <br/>
  (27.6.19 &amp; 2.7.19) I asked Avi to prioritize the tests.
  (3.7.19) Avi said he doesn't have time to test this.
  <br/>
  Note that Adi recently encountered both error variations described in the bug with v2.3.0, so I suspect we might need to reopen the bug; we might also decide to split the bug into separate bugs for the two errors it currently covers.
  <br/>
  &ndash;&gt; <font color="red">**TODO-AVI**</font>
{{< /internal-release-note >}}

<!-- Issues Pending RN-Inclusion Decision -->
{{< internal-release-note title="Issues Pending RN-Inclusion Decision" id="pending-rn-inclusion-decision" >}}

- <a id="Q-ig-expressions"></a>**Expressions** &mdash; we didn't mention any expression changes since the {{< xref s="release-notes" f="version-1.7/v1.7.1.md" a="new-expressions" text="v1.7.1 release notes" >}} &mdash; neither to officially support features previously supported as Tech Preview (such as arrays or the <func>blob</func> function) or to mention new features.
  At least some features were tested and approved by QA, but so far Orit hadn't approved related doc changes.
  We need to create a clear doc plan for the expression features, in Jira, for the next release.
  <br/>
  &ndash;&gt; <font color="red">**TODO-ORIT**</font>;
    <font color="red">**TODO-ADI**</font>
{{< /internal-release-note >}}

<!-- Known Issues for Closed Bugs -->
{{< internal-release-note title="Known Issues for Closed Bugs" id="known-issues-for-closed-bugs" >}}
The bugs for the following known issues were resolved and closed as "Not a bug" or "Won't fix" but Adi wanted to keep the known issues for now:

- <a id="Q-ig-7790"></a>(HA) [The automatic execution of the system-failure recovery process might result in duplicated data for streaming and simple-object data-append operations or duplicated execution of update expressions](#ki-ha-duplicated-data-on-recovery) &mdash; KI for bugs **{{< jira ig="4887" >}}** and **{{< jira ig="7790" >}}**.
  (2.6.19) Orit and Adi confirmed the RN known issue should remain as-is (see the [internal info](#ig-4887-7790) for this note).
{{< /internal-release-note >}}

<!-- //////////////////////////////////////// -->
<!-- New Features and Enhancements -->
{{< rn-heading t="new-and-enhance" >}}

<!-- ---------------------------------------- -->
{{< rn-heading id="new-general" text="General" >}}

- <a id="new-aws-cloud-ga"></a>V2.3.0 is the general-availability (GA) release of Iguazio MLOps Platform for the Amazon Web Services (AWS) cloud.

    {{< internal-release-note docig="12318" id="ig-12318-cloud-ga" >}}
    {{< /internal-release-note >}}

<!-- ---------------------------------------- -->
{{< rn-heading id="new-managed-app-services" text="Managed Application Services" >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="new-web-apis" text="Web APIs" >}}

- <a id="new-web-apis-aws-auth"></a>Added support for authenticating web-API requests by using the authentication syntax of the Amazon Simple Storage Service (S3) API with a platform access key.

    {{< internal-release-note ig="11574" type="req" owner="Ortal L. (ortall)" docig="12002" id="ig-11574" >}}
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="new-jupyter" text="Jupyter Notebook" >}}

- <a id="new-jupyter-v3io-tutorials-raise-version"></a>Raised the preinstalled version of the platform tutorial Jupyter notebooks to v2.3.3.

    {{< internal-release-note ig="7750" type="req" docig="12317" id="ig-7750-doc-ig-12317-jupyter-v3io-tutorials-new-ver" >}}
    {{< /internal-release-note >}}

- <a id="new-jupyter-notebook-gpu-support"></a>Added GPU support for Jupyter Notebook {{< techpreview mark="1" >}}.
  The support includes the option to use the [Horovod](https://github.com/horovod/horovod) open-source framework to run distributed deep-learning jobs, at scale, over NVIDIA GPUs, or to use NVIDIA's [RAPIDS](https://rapids.ai/) open-source libraries suite to run ML models over GPU.
  For more information and assistance, contact [Iguazio Support](https://www.iguazio.com/support/).

    {{< internal-release-note id="ig-11617-11618" >}}
**R&D Tickets:**

- Requirement {{< jira ig="11617" >}}; Sub-Requirements {{< jira ig="11852" >}} (Platform), {{< jira ig="11840" >}} (k8s), and {{< jira ig="11642" >}} (UI)
- Requirement {{< jira ig="11618" >}} (Horovod)<br/>
- Requirement {{< jira ig="12604" >}} (RAPIDS)

**Owners:** Golan S. (golans) (Big-Data); Oded M. (odedm) (Platform); Eliran B (eliranb) (k8s); Eran N. (UI)<br/>
**DOC Issues:** {{< jira ig="12012" >}} (Requirement IG-11617); {{< jira ig="12546" >}} (Requirement IG-11618); {{< jira ig="12605" >}} (Requirement IG-12604)<br/>
<br/>
(sharonl) (1.7.19) In v2.3.0, on k8s systems with GPU, the <gui-title>Resources</gui-title> custom-parameters dashboard tab of the Jupyter Notebook service has a <gui-label>GPU</gui-label> field and the <gui-label>Flavor</gui-label> custom parameter has new GPU flavors &mdash; <gui-label>Deep Learning + GPU</gui-label> (used for Horovod) and <gui-label>Jupyter Deep Learning with Rapids</gui-label> (for RAPIDS); in v2.3.0, the GPU flavors are always displayed, but in v2.5.0 they should be displayed only on systems with GPUs.
When the value of the <gui-label>GPU</gui-label> field is higher than 0, the <gui-label>Deep Learning + GPU</gui-label> flavor should be selected automatically and the non-GPU flavors should be disabled with relevant messages.
I didn't provide details regarding the related UI changes etc., because of the current issues related to this support (see info in DOC IG-12012).
<br/>
The Jupyter Notebook GPU support is _Tech Preview_ for v2.3.0 and the Custom Success team will assist customers who wish to test it.
(1.7.19) Meir changed the status of Requirement IG-11617 to _PARTIALLY TESTED_ and wrote "Alexandra Khazhinsky tested this manually and all the relevant bugs were opened"; he also clarified that RAPIDS wasn't tested.
In consultation with Adi it was decided to keep this as a known issue in v2.3.0.
<br/>
See also the [known issue](#ki-jupyter-rapids-flavor-deployment-error) for the RAPIDS Jupyter Notebook flavor.
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="new-presto" text="Presto" >}}

- <a id="new-presto-optimize-nosql-reads"></a>Optimized performance of NoSQL table queries.

    {{< internal-release-note ig="12040" type="req" owner="Golan S. (golans) / Tal N. (taln)" id="ig-12040-presto" >}}
<br/>
(sharonl) See also the similar [Spark NoSQL DataFrame enhancement](#new-spark-nosql-df-optimize-nosql-reads).
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="new-spark" text="Spark" >}}

<!-- ++++++++++++++++++++++++++++++++++++++++ -->
{{< rn-heading h="5" id="new-spark-nosql-df" text="Spark NoSQL DataFrame" >}}

- <a id="new-spark-nosql-df-optimize-nosql-reads"></a>Optimized performance of NoSQL table queries.

    {{< internal-release-note ig="12040" type="req" owner="Golan S. (golans) / Tal N. (taln)" id="ig-12040-spark" >}}
<br/>
(sharonl) See also the similar [Presto enhancement](#new-presto-optimize-nosql-reads).
<br/>
(9.7.19) The ticket status has changed form _TESTED_ to _DONE_ because QA only tested the feature with Presto and not with Spark.
(10.7.19) Adi decided to keep the Spark enhancement note even though the enhancement wasn't tested by QA.
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="new-tsdb" text="Time-Series Databases (TSDBs)" >}}

<!-- ++++++++++++++++++++++++++++++++++++++++ -->
{{< rn-heading h="5" id="new-tsdb-cli" text="TSDB CLI" >}}

- <a id="new-tsdb-cli-raise-version"></a>Raised the preinstalled version of the V3IO TSDB CLI (<file>tsdbctl</file>) to v0.9.5.

    {{< internal-release-note ig="7750" type="req" docig="12317" id="ig-7750-doc-ig-12317-tsdb-new-ver" >}}
    {{< /internal-release-note >}}

<!-- ++++++++++++++++++++++++++++++++++++++++ -->
{{< rn-heading h="5" id="new-tsdb-nuclio-funcs" text="TSDB Nuclio Functions" >}}

- <a id="new-tsdb-nuclio-funcs-raise-version"></a>Raised the preinstalled version of the V3IO TSDB Nuclio functions to v0.2.1-v0.9.5.
  {{< comment >}}<!-- [IntInfo] (sharonl) (15.8.19) I edited the note
    retroactively to remove the reference to tsdbctl that was mistakenly
    duplicated from the TSDB CLI note and added "V3IO". I also added "V3IO" to
    the previous TSDB CLI version-raise note. -->
  {{< /comment >}}

    {{< internal-release-note ig="7750" type="req" docig="12317" id="ig-7750-doc-ig-12317-tsdb-nuclio-funcs-new-ver" >}}
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="new-frames" text="V3IO Frames" techpreview="1" >}}

- <a id="new-frames-tp-raise-version"></a>Raised the preinstalled version of the V3IO Frames service to v0.5.8-v0.9.5.

    {{< internal-release-note ig="7750" type="req" docig="12317" id="ig-7750-doc-ig-12317-frames-tp-new-ver" >}}
<br/>
(sharonl) (3.7.19) Initially, we also planned to officially support V3IO Frames in platform v2.3.0, but because of newly discovered Frames bugs it was decided to defer the official support &mdash; see Requirement {{< jira ig="11291" >}} / DOC {{< jira ig="12007" >}}.
    {{< /internal-release-note >}}

- <a id="new-tp-frames-tsdb-add-aggregation-window-support"></a>Added an <paramname>aggregationWindow</paramname> parameter to the <func>client.read</func> DataFrame method to support TSDB sliding-window aggregation queries in which the aggregation window differs from the data interval {{< techpreview mark="1" >}}.

    {{< internal-release-note ig="11903" type="req" owner="Golan S. (golans) / Tal N. (taln)" docig="12120" id="ig-11903" >}}
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="new-nuclio" text="Nuclio Serverless Functions" >}}

- <a id="new-nuclio-raise-version"></a>Raised the preinstalled version of the Nuclio serverless framework to 1.1.11.
  {{< comment >}}<!-- [IntInfo] (sharonl) (12.8.19) I fixed the Nuclio version
    retroactively. Originally we thought v2.3.0 used Nuclio v1.10.0 but the RNs
    had a typo (1.1.0). -->
  {{< /comment >}}

    {{< internal-release-note ig="7750" type="req" docig="12317" id="ig-7750-doc-ig-12317-nuclio-new-ver" >}}
    {{< /internal-release-note >}}

- <a id="new-nuclio-s3-code-entry-type-w-authentication"></a>Added a new `S3` code-entry type for retrieving function code from an Amazon S3 bucket, including support for S3 authentication.

    {{< internal-release-note id="ig-11662" >}}
**Requirement:** {{< jira ig="11662" >}}<br/>
**Sub-Requirement:** {{< jira ig="11663" >}} (UI)<br/>
**Owners:** Saar E. (saare) (Platform); Eran N. (UI)<br/>
**DOC Issue:** {{< jira ig="11664" >}}<br/>
<br/>
(sharonl) (30.6.19) In previous releases, you could get function code from an S3 bucket using the `Archive` code-entry type but only for public buckets as we didn't support authentication for S3.
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="new-logging-services" text="Logging and Monitoring Services" >}}

- <a id="new-monitoring-service"></a>Added a default tenant-wide **"Monitoring"** service for viewing performance statistics of serverless Nuclio functions from a Grafana dashboard.
    To view the logs &mdash; from the dashboard <gui-title>Services</gui-title> page, enable the "Monitoring" service (which is disabled by default); create a Grafana service; and select the <gui-label>Nuclio Dashboard</gui-label> UI link for the "Monitoring" service to view the auto-generated <gui-label>Nuclio</gui-label> Grafana dashboard.
    (The <gui-label>Nuclio</gui-label> dashboard can be viewed from the UI of any active platform Grafana service.)

    {{< internal-release-note id="ig-9986" >}}
**Requirement:** {{< jira ig="9986" >}}<br/>
**UI Sub-Requirement:** {{< jira ig="12016" >}}<br/>
**Owners:** Pavel R. (pavelr) (Platform); Eran N. (UI)<br/>
    {{< /internal-release-note >}}

<!-- ---------------------------------------- -->
{{< rn-heading id="new-dashboard" text="Dashboard (UI)" >}}

{{< note id="new-dashboard-other-secs-ref-note" >}}
See the dashboard enhancements in the [Managed Application Services](#new-managed-app-services) new features and enhancements.
{{< /note >}}

- <a id="new-ui-misc-improvements"></a>Implemented miscellaneous cosmetic and text improvements to the dashboard.

    {{< internal-release-note ig="11820" type="req" owner="Eran N. (erann)" docig="12010" id="ig-11820" >}}
    {{< /internal-release-note >}}

- <a id="new-ui-cluster-support-logs-collection"></a>Added the ability for IT administrators to collect and download support logs for the platform clusters from the dashboard.
  Log collection can be triggered for a data cluster from the <gui-title>Clusters</gui-title> home page or from the new data-cluster <gui-title>Support Logs</gui-title> tab, which also displays running and completed log-collection tasks and allows you to download logs for specific data nodes.

    {{< internal-release-note ig="11537" type="req" owner="Eran N. (erann)" docig="12013" id="ig-11537" >}}
<br/>
(sharonl) (10.7.19) The support logs are collected per data node, but the data-node logs also contain logs from the application nodes.
    {{< /internal-release-note >}}

<!-- //////////////////////////////////////// -->
<!-- Fixes -->
{{< rn-heading t="fixes" >}}

The following issues were fixed in the current release:

<!-- ---------------------------------------- -->
{{< rn-heading id="fixes-managed-app-services" text="Managed Application Services" >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="fixes-presto-n-hive" text="Presto and Hive" >}}

- <a id="fix-presto-hive-cfg-changes"></a>To change the Hive configuration parameters of the Presto service (such as changing the path to the MySQL DB), you need to first disable Hive for Presto, apply your changes, re-enable Hive for Presto and set your new Hive configuration, and apply your changes.

    {{< internal-release-note ig="11764" type="bug" ki_start_ver="2.2.0" owner="Igor M. (igorm)" docig="9650" id="ig-11764" >}}
    {{< /internal-release-note >}}

- <a id="fix-web-shell-n-jupyter-restart-to-use-hive"></a>After enabling Hive for the Presto service, existing web-shell and Jupyter Notebook services need to be restarted in order to use Hive.

    {{< internal-release-note owner="Felix G. (felixg)" id="ig-11949" >}}
**Bugs:** {{< jira ig="11949" >}} (web shell); {{< jira ig="12075" >}} (Jupyter Notebook)<br/>
**Owner:** Felix (felixg)<br/>
Known issue since RN v2.2.0<br/>
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="fixes-tsdb" text="Time-Series Databases (TSDBs)" >}}

<!-- ++++++++++++++++++++++++++++++++++++++++ -->
{{< rn-heading h="5" id="fixes-tsdb-cli" text="TSDB CLI" >}}

- <a id="fix-tsdb-cli-create-help-ingestion-rate-d-instead-of-s"></a>The TSDB CLI help text for the <cmd>create</cmd> command's <opt>-r|--ingestion-rate</opt> flag refers to an ingestion-rate unit of days (`d`) instead of seconds (`s`).
V3IO TSDB in the current platform release supports ingestion-rate units of seconds (`s`), minutes (`m`), and hours (`h`).

    {{< internal-release-note ig="12238" type="bug" ki_start_ver="2.1.0" owner="Igor M. (igorm)" docig="9921" id="ig-12238" >}}
<br/>
(sharonl) (27.6.19) Originally, the bug was **TSDB-106**, but it was later converted to {{< jira ig="12238" >}}.
<br/>
(7.5.19) In v2.2.0 (TSDB v0.9.1) and earlier, the description of the ingestion-rate flag in the help text for the CLI <cmd>create</cmd> command refers to a days (`d`) ingestion-rate unit instead of seconds (`s`), even though the examples in the help text use the `s` unit and don't use `d`.
See additional info in Bug IG-12238.
(27.6.19) The bug was fixed in TSDB v0.9.2 and closed for platform v2.3.0 after the fix was verified by QA (Vadim) and me with TSDB v0.9.5.
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="fixes-nuclio" text="Nuclio Serverless Functions" >}}

- <a id="fix-nuclio-ui-focused-field-ignored-in-deployment"></a>Changes to an input field on the <gui-title>Functions</gui-title> dashboard page might not be applied if the field is focused when selecting to deploy the function.

    {{< internal-release-note ig="11350" type="bug" ki_start_ver="2.2.0" owner="Eran N. (erann)" id="ig-11350" >}}
<br/>
(sharonl) (26.5.19) The bug was resolved as fixed in v2.3.0 and assigned to Avi for verification.
    {{< /internal-release-note >}}

- <a id="fix-nuclio-ui-memory-kb-unit"></a>Deploying a function from the dashboard fails when the memory resource is set in KB.

    {{< internal-release-note ig="11972" type="bug" ki_start_ver="2.2.0" owner="Eran N. (erann)" id="ig-11972" >}}
<br/>
(sharonl) (27.5.19) The problem was that the UI sent the request using the unit mark `K` instead of `k` (because of misleading Kubernetes documentation).
    {{< /internal-release-note >}}

- <a id="fix-nuclio-ui-archive-deploy-url-fix-not-applied"></a>After failing to deploy a function from the dashboard using the <opt>Archive</opt> code-entry type because of an invalid URL parameter, subsequent deployments also fail even after the URL is fixed.

    {{< internal-release-note ig="11848" type="bug" ki_start_ver="2.2.0" owner="Sahar E. (sahare)" id="ig-11848" >}}
    {{< /internal-release-note >}}

- <a id="fix-nuclio-ui-build-cfg-readiness-timeout-0"></a>The default <gui-label>Readiness timeout</gui-label> value in the dashboard's function build configuration (0) doesn't reflect the actual default timeout.

    {{< internal-release-note ig="11442" type="bug" ki_start_ver="2.2.0" owner="Eran N. (erann)" id="ig-11442" >}}
<br/>
(sharonl) (2.7.19) In v2.3.0, the default readiness-timeout value changed from 30 to 60 seconds, so in the v2.3.0 fix note I removed "(30 seconds)" from the end of the version that was used in the v2.2.0 known issue.
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="fixes-frames" text="V3IO Frames" techpreview="1" >}}

- <a id="fix-frames-tsdb-create-table-user-auth-failure"></a>User authentication for TSDB table-creation commands fails.
  Use the TSDB CLI to create TSDB tables.

    {{< internal-release-note ig="12256" type="bug" ki_start_ver="2.2.0" owner="Golan S. (golans)" id="ig-12256" >}}
<br/>
(sharonl) (27.6.19) Originally, the bug was **TSDB-116**, but it was later converted to {{< jira ig="12256" >}}.
<br/>
The bug was fixed in V3IO Frames v0.5.4-v0.9.1 and verified by QA in platform v2.3.0 with Frames version v0.5.6-v0.9.5.
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="fixes-logging-services" text="Logging Services" >}}
{{< comment >}}<!-- [IntInfo] (sharonl) (15.8.19) I fixed the anchor ID
  retroactively ("ki" > "fixes"). -->
{{< /comment >}}

- <a id="fix-cloud-elasticsearch-delete-while-used-by-log-forwarder"></a>In cloud environments, it's possible to delete the on-cluster Elasticsearch service while it's being used by the log-forwarder service (despite the related deployment error).

    {{< internal-release-note ig="11788" type="bug" ki_start_ver="2.2.0" owner="Hedii (hedii)" id="ig-11788" >}}
<br/>
(sharonl) (27.5.19) The Elasticsearch service can be created only in cloud environments; it uses the on-cluster Elasticsearch instance that's available only in the cloud environments.
In v2.2.0, attempting to delete an Elasticsearch service that's being used by a log-forwarder service returned an error (deployment error returned from the Platform backend and displayed in the UI), but the pods of the Elasticsearch service were deleted nonetheless.
The bug was fixed and closed in v2.3.0.
The fix was a backend fix to refrain from deleting the service pods when the service is in use.
(I suggested in the bug [comments](https://jira.iguazeng.com/browse/IG-11788?focusedCommentId=48845&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-48845), today, also preventing such a delete operation in the UI, before the deployment stage.)
{{< comment >}}<!-- [c-log-forwarder-elasticsearch-dependency] -->
{{< /comment >}}
    {{< /internal-release-note >}}

- <a id="fix-ui-logs-displayed-w-error-for-unavailable-log-forwarder"></a>When the log-forwarder service is in the "Disabled" or "Failed" state, the <gui-title>Logs</gui-title> dashboard page is displayed with an unknown error.

    {{< internal-release-note ig="11995" type="bug" ki_start_ver="2.2.0" owner="Hedi I. (hedii)" id="ig-11995" >}}
    {{< /internal-release-note >}}

<!-- ---------------------------------------- -->
{{< rn-heading id="fixes-ha" text="High Availability (HA)" >}}

- <a id="fix-ha-main-k8s-master-app-node-failure-non-cloud"></a>In non-cloud environments, in case of failure in the main master application node of a Kubernetes application cluster, the platform's access to the application nodes is lost and it can no longer manage the cluster's application services.
  Previously run application services will continue to run but cannot be stopped, and new services cannot be created.

    {{< internal-release-note ig="11774" type="bug" owner="Ilan G. (ilang)" id="ig-11774" >}}
<br/>
(sharonl) (10.7.19) See the related [known issue](#ki-ha-main-k8s-master-app-node-failure-cloud) for cloud environments.
    {{< /internal-release-note >}}

<!-- ---------------------------------------- -->
{{< rn-heading id="fixes-platform-mgmt" text="Platform Management" >}}

- <a id="fix-large-containers-deletion-failure-ig-7954"></a>Deletion of very large containers, which contain hundreds of millions of objects, might fail.

    {{< internal-release-note ig="7954" type="bug" ki_start_ver="1.7.0" owner="Gilad (giladb)" id="ig-7954" >}}
    {{< /internal-release-note >}}

<!-- ---------------------------------------- -->
{{< rn-heading id="fixes-dashboard" text="Dashboard (UI)" >}}

{{< note id="fixes-dashboard-nuclio-note" >}}
For <gui-title>Functions</gui-title> dashboard-page fixes, see the [Nuclio Serverless Functions](#fixes-nuclio) fixes.
{{< /note >}}

- <a id="fix-ui-new-dir-name-w-spaces-at-start-or-end"></a>When creating a new directory, spaces at the start or end of the directory name are automatically trimmed.
  Consequently, it's also not possible to create from the dashboard a directory whose name contains only spaces.

    {{< internal-release-note id="ig-9818" >}}
**Bugs:** {{< jira ig="9818" >}} (space-only file name produces an error); {{< jira ig="9819" >}} (spaces at the start and end of directory names are trimmed.<br/>
**Owner:** Eran N. (erann)<br/>
Known issue since RN v2.1.0<br/>
    {{< /internal-release-note >}}

- <a id="fix-ui-spark-create-from-other-service-cfg"></a>Creation of a Spark service from the configuration of another service (Jupyter Notebook / Zeppelin / web shell) occasionally fails.

    {{< internal-release-note ig="11521" type="bug" ki_start_ver="2.2.0" owner="Eran N. (erann)" id="ig-11521" >}}
    {{< /internal-release-note >}}

- <a id="fix-ui-zeppelin-service-spark-req-not-enforced"></a>The dashboard doesn't prevent creating a Zeppelin service without a Spark-service configuration, even though such a service will fail to deploy.
    {{< internal-release-note ig="12076" type="bug" ki_start_ver="2.2.0" owner="Eran N. (erann)" id="ig-12076" >}}
<br/>
(sharonl) (29.5.19) This v2.2.0 RNs known issue replaced the v2.1.0 RNs known issue for Bug {{< jira ig="11031" >}} "[Services] make spark field mandatory for zeppelin", which was resolved and closed in 2.2.0 but the fix was only on the Platform backend side &mdash; return a relevant error (which is also displayed in the UI) when attempting to deploy a Zeppelin service without a Spark configuration.
V2.3.0 Bug {{< jira ig="12076" >}} was opened today to enforce the Zeppelin service's Spark parameter requirement in the UI.
I decided not to document a fix for the v2.1.0 (and earlier RNs known issue for Bug IG-11031) in the 2.2.0 RNs, I just replaced that known issue with a UI specific issue.
<br/>
(27.6.19) Bug IG-12076 was resolved as fixed and closed in v2.3.0, therefore the known issue was moved to the **Fixes** section in the current 2.3.0 RNs.
    {{< /internal-release-note >}}
{{< comment >}}<!-- [c-zeppelin-service-needs-spark] -->
{{< /comment >}}

<!-- //////////////////////////////////////// -->
<!-- Known Issues -->
{{< rn-heading t="known-issues" >}}

<!-- ---------------------------------------- -->
{{< rn-heading id="ki-managed-app-services" text="Managed Application Services" >}}
{{< comment >}}<!-- [IntInfo] (sharonl) (12.5.19) At Adi's request, I removed
  the note that I previously added here to refer to the dashboard known issues
  for UI issues related to services. -->
{{< /comment >}}

- <a id="ki-services-failure-for-reused-usernames"></a>A user whose username was previously in use in the platform cannot run application services.

    {{< internal-release-note ig="11202" type="bug" ki_start_ver="2.0.0" owner="Orit N. (oritn)" docig="10843" id="ig-11202" >}}
<br/>
(sharonl) (21.3.19) In consultation with Adi, I documented this only as a known issue in the release notes, but not in other doc locations.
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="ki-web-apis" text="Web APIs" >}}

<!-- ++++++++++++++++++++++++++++++++++++++++ -->
{{< rn-heading h="5" id="ki-simple-object-web-api" text="Simple-Object Web API" >}}

- <a id="ki-s3-web-api-get-service-ret-container-id-not-name"></a>The <api>GET Service</api> operation for listing containers may sometimes return the container ID in place of the container name.

    {{< internal-release-note ig="3027" type="bug" owner="Gilad (giladb)" ki_start_ver="1.0.0" id="ig-3027" >}}
<br/>
(sharonl) Bug 3027 was closed in v1.5.0 as "Won't Fix".
(25.12.17) Gilad explained that it was closed because eventually (although we don't currently know in which version) we will change the design and only expose container names to the user, which will make this bug irrelevant, so it's not worth the fix effort.
Adi confirmed that we should continue documenting this as a known issue in the release notes until the relevant design changes are made.
<br/>
(24.2.18) After speaking with Gilad, it turns out that we now have v1.7.0 Task {{< jira ig="5346" >}} **"eliminate container handle semantics in v3io ..."** for supporting only container names and removing the support for container IDs (handles).
<br/>
(25.5.20) {{< jira ig="5346" >}} was done in v2.2.0.
I confirmed with Assaf B. that **the bug doesn't exist since v2.2.0**.
However, as I missed this in the v2.2.0&ndash;2.5.0 release notes (because the KI was connected to Bug IG-3027 and not to Task IG-5346), it still appears (incorrectly) as a known issue in these release notes.
In the v2.8.0 release notes I removed this KI.
I didn't replace it with a fix note because the fix was done in v2.2.0.
    {{< /internal-release-note >}}
    {{< comment >}}<!-- (sharonl) (29.1.18) In the initial v1.0.0 RNs, this was
      incorrectly documented as a Container Management API <api>List
      Containers</api> bug. When preparing the v1.5.0 RNs, I found that the bug
      is in our GET Service AWS S3-equivalent web-API operation, so I also
      retroactively edited the v1.0.0 RN in the new web documentation. -->
    {{< /comment >}}

- <a id="ki-s3-web-api-get-n-head-object-wrong-ret-data"></a><api>GET Object</api> and <api>HEAD Object</api> operations don't return correct `ETag` and `Content-Type` metadata, and <api>GET Object</api> also doesn't return the correct `Last-Modified` metadata.

    {{< internal-release-note id="ig-3451-3453" >}}
**Bugs:** {{< jira ig="3451" >}}; {{< jira ig="3453" >}} (ETag)<br/>
**Owner:** Gilad (giladb)<br/>
Known issue since RN v1.0.0 (`ETag` &mdash; RN phrased differently) and v1.5.0 (the rest, although the bugs probably also exist in earlier releases)
    {{< /internal-release-note >}}

<!-- ++++++++++++++++++++++++++++++++++++++++ -->
{{< rn-heading h="5" id="ki-streaming-web-api" text="Streaming Web API" >}}

-	<a id="ki-putrecords-for-non-stream-dir-error-ig-4310"></a><api>PutRecords</api> with a stream path that points to an existing non-stream directory returns error <api>ResourceNotFoundException</api> instead of <api>ResourceIsnotStream</api>.

    {{< internal-release-note ig="4310" owner="Ortal (ortall)" ki_start_ver="1.0.0" >}}
    {{< /internal-release-note >}}

-	<a id="ki-web-invalid-updatestream-req-body-resp-error"></a><api>UpdateStream</api> with an invalid request-body JSON format may not return the expected <api>InvalidArgumentException</api> error.

    {{< internal-release-note ig="4310" owner="Ortal (ortall)" ki_start_ver="1.0.0" >}}
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="ki-jupyter" text="Jupyter Notebook" >}}

- <a id="ki-jupyter-notebooks-scala-not-supported"></a>Running Scala code from a Jupyter notebook isn't supported in the current release.
  Instead, run Scala code from a Zeppelin notebook or by using <file>spark-submit</file>, or use Python.

    {{< internal-release-note ig="11174" type="bug" ki_start_ver="2.0.0" owner="Gal T. (galt)" docig="10216" id="ig-11174" >}}
<br/>
(sharonl) This is documented also in the **Software Specifications and Restrictions** and in other locations in the doc.
{{< comment >}}<!-- [c-jupyter-notebooks-scala-not-supported] -->
{{< /comment >}}
    {{< /internal-release-note >}}

- <a id="ki-jupyter-rapids-flavor-deployment-error"></a>Successful deployment of a Jupyter Notebook service with the <gui-label>Jupyter Deep Learning with Rapids</gui-label> flavor {{< techpreview mark="1" >}} requires preliminary installation.
  Contact [Iguazio Support](https://www.iguazio.com/support/) before attempting to use this flavor.

    {{< internal-release-note ig="12549" type="bug" ki_start_ver="2.3.0" owner="Golan S. (golans)" docig="12012" id="ig-12549" >}}
<br/>
(sharonl) (4.8.19) The bug was fixed in v2.5.0 and is currently pending QA verification.
Note that in v2.5.0, the dedicated RAPIDS Jupyter GPU flavor will be removed and we'll only have two flavors &mdash; with and without GPU support; see Requirement {{< jira ig="12694" >}}.
{{< comment >}}<!-- [c-jupyter-nb-rapids-flavor-deployment-failure] [IntInfo]
  See also the GPU section in the ecosystem.md intro doc. -->
{{< /comment >}}
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="ki-presto-n-hive" text="Presto and Hive" >}}

- <a id="ki-presto-hive-username-cant-be-changed-for-existing-db"></a>You can't change the MySQL DB user for an existing Hive MySQL DB.
  To change the user, you need to either reconfigure Hive for Presto to set a different DB path that doesn't yet exist (in addition to the different user); or disable Hive for Presto, apply your changes, delete the current MySQL DB directory (using a file-system command), and then re-enable Hive for Presto and configure the same DB path with a new user.
  {{< comment >}}<!-- [IntInfo] (sharonl) (18.8.19) I retroactively edited the
    note to remove ", subject to the [Hive reconfiguration
    restrictions](#ki-presto-hive-cfg-changes)" from the first part of the
    sentence (before the semicolon) because the linked known issue was fixed in
    v2.3.0 (see #fix-presto-hive-cfg-changes in the v2.3.0 release notes). -->
  {{< /comment >}}

    {{< internal-release-note ig="11757" type="bug" ki_start_ver="2.2.0" owner="Golan S. (golans)" docig="9650" id="ig-11757" >}}
    {{< /internal-release-note >}}

- <a id="ki-presto-nosql-table-view-restricted-to-view-creator"></a>A NoSQL-table view can be used only by the user who created the view.

    {{< internal-release-note ig="11971" type="bug" ki_start_ver="2.2.0" owner="Igor M. (igorm)" id="ig-11971" >}}
<br/>
(1.7.19) The bug was resolved as fixed in v2.3.0, but Avi reopened it after encountering an error when trying to verify the fix.
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="ki-spark" text="Spark" >}}

<!-- ++++++++++++++++++++++++++++++++++++++++ -->
{{< rn-heading h="5" id="ki-spark-ui" text="Spark UI" >}}

- <a id="ki-spark-ui-broken-links-after-app-kill"></a>The Spark UI might display broken links after killing a running application from the UI.
  To resolve this, close the current Spark UI browser tab and reopen the UI in a new tab.

    {{< internal-release-note ig="12143" type="bug" ki_start_ver="2.3.0" owner="Uri H. (urih)" id="ig-12143" >}}
    {{< /internal-release-note >}}

<!-- ++++++++++++++++++++++++++++++++++++++++ -->
{{< rn-heading h="5" id="ki-spark-streaming" text="Spark Streaming" >}}

- <a id="ki-spark-streaming-consume-after-shard-count-increase-ig-6471"></a>To consume records from new shards after increasing a stream's shard count, you must first restart the Spark Streaming consumer application.

    {{< internal-release-note ig="6471" type="bug" owner="Golan (golans)" docig="7157" ki_start_ver="1.5.3" id="ig-6471" >}}
<br/>
(sharonl) The shard-count increase can currently be done only using the <api>UpdateStream</api> Streaming Web API operation.
<br/>
This bug exists also in earlier versions but was discovered only before the v1.5.3 release and the v1.5.0 documentation publication, and therefore added to the RNs only in v1.5.3 + added to the **Software Specifications and Restrictions** and <api>UpdateStream</api> Streaming Web API reference documentation in v1.5.0 and retroactively also in the v1.0.3 reference &mdash; see DOC Task {{< jira ig="7157" >}}.
    {{< /internal-release-note >}}
    {{< comment >}}<!-- [c-spark-streaming-consume-after-shard-increase] -->
    {{< /comment >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="ki-tsdb" text="Time-Series Databases (TSDBs)" >}}

- <a id="ki-tsdb-prev-interop-last-data-point"></a>SQL queries with `prev` interpolation might not return data for the last data point when no newer sample data is available.

    {{< internal-release-note ig="12235" type="bug" ki_start_ver="2.1.0" owner="Tal N. (taln)" id="ig-12235" >}}
<br/>
(sharonl) (27.6.19) Originally, the bug was **TSDB-109**, but it was later converted to {{< jira ig="12235" >}}.
    {{< /internal-release-note >}}

<!-- ++++++++++++++++++++++++++++++++++++++++ -->
{{< rn-heading h="5" id="ki-tsdb-prometheus" text="Prometheus" >}}

- <a id="ki-tsdb-prometheus-service-change-to-invalid-path"></a>Changing the TSDB-table configuration for an existing Prometheus service to an invalid path doesn't return a deployment error.

    {{< internal-release-note ig="12187" type="bug" owner="Golan S. (golans)" docig="10843" id="ig-12187" >}}
Known issue since RN v2.2.0 / TSDB v0.9.2<br/>
<br/>
(sharonl) (6.6.19) The previous known issue of succeeding to create a new Prometheus table with an invalid TSDB table path was {{< xref s="release-notes" f="version-2.2/v2.2.0.md" text="v2.2.0 release notes" a="fix-tsdb-prometheus-service-create-for-non-existent-tsdb-table" text="fixed" >}} in v2.2.0.
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="ki-nuclio" text="Nuclio Serverless Functions" >}}

- <a id="ki-nuclio-unsupported-dark-site-langs"></a>Function deployment for the Ruby, Java, and Node.js runtimes isn't supported for platform installations without an internet connection (offline installations).

    {{< internal-release-note ig="11148" type="bug" ki_start_ver="2.0.0" owner="Oded M. (odedm)" id="ig-11148" >}}
<br/>
(sharonl) (10.7.19) In the v2.3.0 release notes, I moved this known issue out of the "TSDB Nuclio Functions" subsection (as the bug applies to all Nuclio functions), and I merged this retroactively to the v2.0.0&ndash;v2.2.0 release notes (only in the v2.3.0+ sites).
    {{< /internal-release-note >}}

- <a id="ki-nuclio-ui-error-for-successful-deployment-after-prev-timeout-failure"></a>In case of a successful automatic deployment of a Nuclio function for a request that previously timed out &mdash; for example, if a requested resource, such as a GPU, becomes available after the time-out failure &mdash; the function status in the dashboard is still <gui-label>Error</gui-label>.

    {{< internal-release-note ig="12487" type="bug" ki_start_ver="2.3.0" owner="Adi H. (adih)" id="ig-12487" >}}
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="ki-frames" text="V3IO Frames" techpreview="1" >}}

- <a id="ki-frames-blob-attr-no-support"></a>Item attributes (DataFrame columns) of type blob are not supported.

    {{< internal-release-note ig="12603" type="bug" ki_start_ver="2.3.0" owner="Tal N. (taln)" docig="12317" id="ig-12603" >}}
<br/>
(sharonl) (8.7.19) This is also documented as a restriction in the **Software Specifications and Restrictions**.
    {{< comment >}}<!-- [c-frames-blob-attr-no-support] -->
    {{< /comment >}}
    {{< /internal-release-note >}}

<!-- ++++++++++++++++++++++++++++++++++++++++ -->
{{< rn-heading h="5" id="ki-frames-nosql" text="Frames NoSQL DataFrame (&quot;kv&quot; Backend)" >}}

- <a id="ki-frames-kv-key-not-written-as-user-attr"></a>When writing a DataFrame, the index column (primary-key attribute) isn't written to the table as a user attribute and therefore isn't returned when reading from the table with another API, such as Spark DataFrames or Presto.

    {{< internal-release-note ig="12574" type="bug" ki_start_ver="2.3.0" owner="Tal N. (taln)" id="ig-12574" >}}
<br/>
(sharonl) (9.7.19) Frames reads in v2.3.0 are OK, because we check the item names (<attr>__name</attr>) and display them to the user in a column named according to the schema <jsonkey>key</jsonkey> value &mdash; i.e., the name of the index column.
<br/>
A [fix PR](https://github.com/v3io/frames/pull/249) has been merged and should be part of the next Frames release (expected to be Frames v0.5.9-v0.9.5) / platform v2.3.1; the status of Bug IG-12574 has been set to _INTEGRATION-READY_.
    {{< /internal-release-note >}}

- <a id="ki-frames-kv-write-w-time-attr-spark-df-n-presto-read-err"></a>pandas <api>datetime</api> item attributes that are written with Frames cannot be read with Spark DataFrames or Presto.

    {{< internal-release-note ig="12559" type="bug" ki_start_ver="2.3.0" owner="Tal N. (taln)" id="ig-12559" >}}
<br/>
(sharonl) (9.7.19) Frames sets the attribute type of pandas <api>datetime</api> attributes to `time`, which isn't recognized by Spark DFs and Presto.
Attempting to read such attributes with Spark or Presto results in an error.
    {{< /internal-release-note >}}

- <a id="ki-frames-kv-read-timestamp-attr"></a>Timestamp item attributes that are written with a Spark DataFrame aren't returned when reading the table with Frames.

    {{< internal-release-note ig="12671" type="bug" ki_start_ver="2.3.0" owner="Tal N. (taln)" id="ig-12671" >}}
    {{< /internal-release-note >}}

- <a id="ki-frames-kv-write-df-wo-index-col-wrong-item-names"></a>When writing a DataFrame without explicitly setting the index column, the item names in the table are set incorrectly to the values of the first regular DataFrame column (user attribute) and the table doesn't contain a primary-key user attribute.

    {{< internal-release-note ig="12132" type="bug" ki_start_ver="2.3.0" owner="Tal N. (taln)" id="ig-12132" >}}
    {{< /internal-release-note >}}

- <a id="ki-frames-kv-infer-schema-wo-key-param"></a>When inferring the table schema without setting the <paramname>key</paramname> parameter of the client <func>execute</func> <cmd>infer</cmd> command, the schema key isn't set to the name of the table's primary-key attribute.
  Consequently, the table can't be read with Spark DataFrames or Presto, and reading the table with Frames returns an extra <attr>\_\_name</attr> attribute (column), in addition to the primary-key attribute that contains the same values.

    {{< internal-release-note ig="12619" type="bug" ki_start_ver="2.3.0" owner="Golan S. (golans)" id="ig-12619" >}}
<br/>
(sharonl) (17.10.19) I fixed the Requirement number in the internal info retroactively (IG-12620 &gt; IG-12619).
    {{< /internal-release-note >}}

- <a id="ki-fames-kv-int-read-as-float"></a>Integer attribute values are read by Frames as floating-point numbers.

    {{< internal-release-note ig="12670" type="bug" ki_start_ver="2.3.0" owner="Golan S. (golans)" id="ig-12670" >}}
<br/>
A [fix PR](https://github.com/v3io/frames/pull/249) has been merged and should be part of the next Frames release (expected to be Frames v0.5.9-v0.9.5) / platform v2.3.1; the status of Bug IG-12574 has been set to _INTEGRATION-READY_.
    {{< /internal-release-note >}}

<!-- ======================================== -->
{{< rn-heading h="4" id="ki-hadoop" text="Hadoop" >}}

-	<a id="ki-hadoop-unsupported-hdfs-commands"></a>The following Hadoop (`hdfs`) commands aren't supported:
    <cmd>createSnapshot</cmd>, <cmd>deleteSnapshot</cmd>, <cmd>getfattr</cmd>, <cmd>setfattr</cmd>, <cmd>setfacl</cmd>, and <cmd>setrep</cmd>.
  <br/>
  The <cmd>truncate</cmd> command is supported as {{< techpreview fmt="0" >}}.

    {{< internal-release-note ki_start_ver="1.0.0" id="hdfs-unsupported-cmds" >}}
<br/>
(sharonl) (26.6.18) Initially, this known issue included the <cmd>truncate</cmd> command and was associated with Bug {{< jira ig="3106" >}} to implement this command.
Bug 3106 and duplicate Bug {{< jira ig="5239" >}} were resolved in v1.7.0 as {{< techpreview fmt="0" >}} (not tested by QA), at which point I documented the support for <cmd>truncate</cmd> as an {{< xref s="release-notes" f="version-1.7/v1.7.1.md" a="ig-3106" text="enhancement" >}} in the v1.7.1 (v1.7 GA) release notes, removed the reference to the command from the known-issue note, and disassociated the known-issue note from Bug 3106.
The changes were done after the initial publication of the v1.7.0 Equinix Early Edition release notes.
<br/>
Golan said there's no Jira ticket to support the other commands.
<br/>
(2.5.19) <cmd>truncate</cmd> still hasn't been tested by QA.
In the v2.1.0 release notes, following Meir's input and in consultation with Adi, I added the reference to the {{< techpreview fmt="0" >}} support for the <cmd>truncate</cmd> to the unsupported-commands known issue.
    {{< /internal-release-note >}}

<!-- ---------------------------------------- -->
{{< rn-heading id="ki-file-system" text="File System" >}}

{{< note id="ki-file-system-hadoop-fs-note" >}}
For Hadoop FS known issues, see the [Hadoop known issues](#ki-hadoop).
{{< /note >}}

-	<a id="ki-fs-ops-no-stream-shard-sup"></a>File-system operations are not supported for stream shards.

    {{< internal-release-note ig="3604" type="task" owner="Gilad (giladb)" ki_start_ver="1.0.0" id="ig-3604" >}}
    {{< /internal-release-note >}}

<!-- ---------------------------------------- -->
{{< rn-heading id="ki-backup-n-recovery" text="Backup and Recovery" >}}

- <a id="ki-stream-data-no-backup"></a>Stream data is not backed up and restored as part of the platform's backup and upgrade operations.

    {{< internal-release-note ki_start_ver="1.5.1" >}}
<br/>
(sharonl) (13.2.18) Adi requested that we document this as a known issue in the RNs even though this behavior is by design and currently there's no plan to change it.
This is also documented in the **Software Specifications and Restrictions** document (DOC Task {{< jira ig="3582" >}}).
    {{< /internal-release-note >}}

<!-- ---------------------------------------- -->
{{< rn-heading id="ki-ha" text="High Availability (HA)" >}}

- <a id="ki-ha-main-k8s-master-app-node-failure-cloud"></a>In cloud environments, in case of failure in the main master application node of a Kubernetes application cluster, the platform's access to the application nodes is lost and it can no longer manage the cluster's application services.
  Previously run application services will continue to run but cannot be stopped, and new services cannot be created.

    {{< internal-release-note rnid="ki-ha-main-k8s-master-app-node-failure-cloud" id="ig-12573-12636" >}}
**R&D Tickets:** Bug {{< jira ig="12573" >}} ("cloud - vip became broken") (v2.5.0; deferred from v2.3.1); Requirement {{< jira ig="12636" >}} ("ki-ha-main-k8s-master-app-node-failure-cloud") (v2.8.0); {{< jira ig="13840" >}} "Azure changes for Pacemaker" (v3.0.0)<br/>
**Owners:** Gal Z. (galz) (IG-12573); Gal Z. (galz) (IG-12636); Alez P. (alexp) (IG-13840)<br/>
Known issue since RN v2.1.0 for all environments; restricted in RN v2.3.0 to the cloud<br/>
<br/>
(sharonl) (10.7.19) In the **v2.1.0 &amp; v2.2.0** release notes we had a known issue for this HA bug that wasn't restricted to cloud environments.
The known issue was for Bug {{< jira ig="11774" >}}.
In **v2.3.0**, this bug was fixed only for non-cloud environments and Bug {{< jira ig="12573" >}} and Requirement {{< jira ig="12636" >}} were opened for the remaining cloud issues.
=> In the v2.3.0 release notes, I restricted the known issue to cloud environments and linked it to the new cloud tickets, and I added a {{< xref s="release-notes" f="version-2.3/v2.3.0.md" a="fix-ha-main-k8s-master-app-node-failure-non-cloud" text="fix note" >}} for non-cloud environments.
(24.5.20) In **v2.8.0**, the KI was fixed for AWS as part of Requirement {{< jira ig="12636" >}}, which was then modified not to cover Azure and a separate v3.0.0 Requirement {{< jira ig="13840" >}} was opened for Azure cloud deployment changes that should also fix this KI, and the RN KI was modified accordingly and tagged `#ki-ha-main-k8s-master-app-node-failure-cloud-azure`; see also the v2.8.0 RNs `#fix-cloud-vip-aws` fix note.
{{< comment >}}<!-- [InfInfo] (sharonl) (20.5.20) I retroactively fixed the
  RN ID in the internal-release-note `rnid` field. (24.5.20) I updated the
  internal info. -->
{{< /comment >}}
    {{< /internal-release-note >}}

- <a id="ki-ha-duplicated-data-on-recovery"></a>The automatic execution of the system-failure recovery process might result in duplicated data for streaming and simple-object data-append operations or duplicated execution of update expressions.

    {{< internal-release-note id="ig-4887-7790" >}}
**Bugs:** {{< jira ig="4887" >}} (streaming &amp; S3 data append); {{< jira ig="7790" >}} (update expressions)<br/>
**Owner:** Gilad (giladb)<br/>
Known issue since RN v1.5.0 for Bug {{< jira ig="4887" >}} and since RN v1.7.0 also for Bug {{< jira ig="7790" >}} (update-expression addition).<br/>
<br/>
(sharonl) This issue is also documented in the **"Software Specifications and Restrictions"** doc (`#duplicated-sys-failure-recovery-data`).
<br/>
(27.2.19) Bug {{< jira ig="7790" >}} has now been closed as _Won't Fix_.
Ori wrote in the comments "This is a know arch limitation of the system, at this point one can use the conditional update with the mtime returned on the command".
(2.6.19) Orit confirmed that the issue persists in v2.2.0 and she and Adi said to keep the known issue in the release notes as-is (see also this IG-7790 [comment](https://jira.iguazeng.com/browse/IG-7790?focusedCommentId=44092&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-44092) in Bug {{< jira ig="7790" >}}).
Orit wrote that this issue isn't related to the app nodes but rather the data path.
    {{< /internal-release-note >}}

- <a id="ki-ha-getitems-failure-ig-6475"></a>The <api>GetItems</api> NoSQL Web API operation might fail during failover.

    {{< internal-release-note ig="6475" type="bug" owner="Roy B. (royb)" ki_start_ver="1.7.0" id="ig-6475" >}}
<br/>
(sharonl) (26.2.19) In previous release notes we had a combined HA known issue for bugs {{< jira ig="6475" >}} and {{< jira ig="6246" >}}, phrased generically as "I/O requests might fail during failover.", per Ori's guideline (see, for example, the {{< xref s="release-notes" f="version-1.9/v1.9.5.md" a="ki-ha-io-requests-failure-ig-6475-6246" text="v1.9.5 RNs" >}}) and the details in the bugs' _Release Note Information_).
In v2.0.0, Bug IG-6246 was fixed and closed, but Bug IG-6475 is still open and was deferred to v2.4.0.
Roy B. and Ortal confirmed that the remaining known issue for Bug IG-6475 is only for the <api>GetItems</api> NoSQL Web API operation.
Therefore, I rephrased the known issue and created a {{< xref s="release-notes" f="version-2.0/v2.0.0.md" text="v2.0.0 release notes" a="fix-ha-io-stream-requests-failure-ig-6246" text="fix RN" >}} for Bug IG-6246.
    {{< /internal-release-note >}}

<!-- ---------------------------------------- -->
{{< rn-heading id="ki-security-n-user-management" text="Security and User Management" >}}

- <a id="ki-data-access-policy-perm-check-cur-dir-only"></a>Data-access policy permissions are checked only for the current directory and not for the entire path.

    {{< internal-release-note ig="8733" type="req" ki_start_ver="1.7.2" owner="Roy B. (royb)" id="ig-8733" >}}
<br/>
(sharonl) (30.8.18) In the v1.7.2 RNs, we connected the similar known issue to Bug {{< jira ig="8726" >}}, which has since then been resolved as a duplicate of Bug {{< jira ig="8733" >}}.
Therefore, I connected the v1.9.4 (v1.9 GA) known issue to the open bug (IG-8733).
(24.4.19) IG-8733 is still open but doesn't have a target version.
(Previously, it was planned for v2.0.0, which has since then been released).
<br/>
(26.7.19) The ticket type is "Requirement" and not "Bug", as indicated in the internal info for previous release notes.
Perhaps it was originally a bug and was then converted to a requirement.
    {{< /internal-release-note >}}

- <a id="ki-data-access-policy-sources-not-supported"></a>The data-access policy rule <gui-label>Sources</gui-label> match condition, for specifying interface or network sources, isn't supported.

    {{< internal-release-note id="ig-12302-8414" >}}
**Bugs:** {{< jira ig="12302" >}} (interface sources); {{< jira ig="8414" >}} (network sources)<br/>
**Owners:** Ortal L. (ortall) (IG-12302); Orit N. (orinn) (IG-8414)<br/>
Known issue since RN v2.3.0 but the bugs also exist in earlier releases<br/>
<br/>
(sharonl) (10.7.19) In v2.x, all I/O requests for the platform services are identified as web-API requests (<gui-label>Web</gui-label> data-access policy interface source) &mdash; Bug {{< jira ig="12302" >}}; therefore, the <gui-label>Interface</gui-label> data-access-policy rule source doesn't work as expected and isn't helpful to distinguish between request sources.
In addition, at least since v1.7.2, the data-access policy rule network source (<gui-label>Network Sources</gui-label>) doesn't work &mdash; Bug {{< jira ig="8414" >}}.
<br/>
This issue is also documented in the non-RN docs, including retroactively in the published documentation for relevant previous releases.
{{< comment >}}<!-- [c-data-access-policy-sources-bug-interfaces]
  [c-data-access-policy-sources-bug-network] -->
{{< /comment >}}
    {{< /internal-release-note >}}

<!-- ---------------------------------------- -->
{{< rn-heading id="ki-platform-mgmt" text="Platform Management" >}}

- <a id="ki-create-container-bad-id-error"></a><api>Create Container</api> requests with a negative container ID may result in response status code 500 instead of 400 and a cumbersome error message.

    {{< internal-release-note ig="6118" type="bug" ki_start_ver="1.9.4" owner="Oded M. (odedm)" id="ig-6118" >}}
    {{< /internal-release-note >}}

<!-- ---------------------------------------- -->
{{< rn-heading id="ki-dashboard" text="Dashboard (UI)" >}}

{{< note id="ki-dashboard-other-ki-secs-ref-note" >}}
See the [Nuclio known issues](#ki-nuclio) for Nuclio-specific dashboard issues.
{{< /note >}}

- <a id="ki-ui-server-or-site-cant-be-reached"></a>The dashboard might occasionally display an unreachable server or site error, specifically after an expired browser session, which can be resolved only by refreshing the browser page.

    {{< internal-release-note ig="11717" type="bug" ki_start_ver="2.1.0" owner="Eran N. (erann)" id="ig-11717" >}}
<br/>
(2.7.19) The bug was resolved as fixed in v2.3.0 and is currently assigned to Avi for verification of the fix.
Adi encountered similar errors with v2.3.0, despite the supposed fix.
Therefore, for now, we kept this known issue also in the v2.3.0 release notes.
See the related [internal release-note comment](#Q-ig-11717).
    {{< /internal-release-note >}}

- <a id="ki-ui-used-capacity-long-refresh-in-loaded-systems"></a>In heavily loaded systems, the container used-capacity information might take a long time to refresh.

    {{< internal-release-note ig="5633" type="bug" ki_start_ver="1.7.0" owner="Pavel (pavelr)" id="ig-5633" >}}
<br/>
(21.10.18) In the v1.7 RNs, internally we initially connected this known issue incorrectly to Bug {{< jira ig="7883" >}}.
We discovered the error when we prepared the v1.9.4 (v1.9 GA) RNs, and Ori said that because there's no dedicated bug for this issue, we should connect the issue, for now, to the "KV for file system" Requirement {{< jira ig="5633" >}} &mdash; as implementing and integrating this solution is a prerequisite to resolving the known issue.
    {{< /internal-release-note >}}

- <a id="ki-ui-service-user-change-not-applied-to-open-tabs"></a>When logging into a service as a different user than the logged in dashboard user, previously opened dashboard tabs need to be manually refreshed to reflect the new user.

    {{< internal-release-note ig="11231" type="bug" ki_start_ver="2.1.0" owner="Eran N. (erann)" id="ig-11231" >}}
<br/>
(27.6.19) The bug was resolved as fixed in v2.5.0, currently pending QA verification.
    {{< /internal-release-note >}}

- <a id="ki-ui-nuclio-n-monitoring-services-resources-cfg"></a>It's possible to edit the memory and CPU resources of the default Nuclio and Monitoring services from the dashboard's <gui-title>Common Parameters</gui-title> service tab.
  Users should refrain from editing the resources of these services.

    {{< internal-release-note ig="11808" type="req" owner="Eran N. (erann)" id="ig-11808" >}}
<br/>
Known issue since RN v2.1.0 for Nuclio and since v2.3.0 also for Monitoring.
<br/>
(sharonl) (2.7.19) Requirement IG-11808 was deferred to v2.5.0 and is currently assigned to Adi so he can define how to implement the elimination of the option to edit these service's resources.
{{< comment >}}<!-- [c-ki-ui-nuclio-service-resources-cfg]
  [c-ki-ui-monitoring-service-resources-cfg] -->
{{< /comment >}}
    {{< /internal-release-note >}}

- <a id="ki-ui-attr-name-w-underscore-no-edit"></a>An item attribute whose names contains an underscore (`_`) cannot be edited from the dashboard.

    {{< internal-release-note ig="12683" type="bug" ki_start_ver="2.3.0" owner="Eran N. (erann)" id="ig-12683" >}}
<br/>
(sharonl) (10.7.19) The bug was reported by Singtel before the v2.3.0 release and is therefore documented only beginning with the  v2.3.0 release notes, but it was also a bug in previous releases.
The bug has now been resolved as fixed in v2.5.0 (pending QA verification); I asked Eran to merge the fix also to v2.3.1.
    {{< /internal-release-note >}}

{{< comment >}}<!-- [IntInfo] (sharonl) (25.5.20) I retroactively removed the
  filtered-out EMR KIs section (not part of the published RNs). See details in
  IG-7701 and IG-7695. -->
{{< /comment >}}

<!-- //////////////////////////////////////// -->
<!-- Notes -->
{{< rn-heading t="notes" >}}

- <a id="note-coordinated-platform-actions"></a>Platform start-up and upgrade actions should be coordinated with the Iguazio support team.

    {{< internal-release-note docig="5829" >}}
<br/>
(sharonl) (2.4.18) Adi requested that we add this in the release notes (starting with the v1.5.3 RNs, even though it's also true for earlier versions).
(20.3.19) At Maor's request, I rephrased the previous note to replace "restart, and shut-down" with "start-up and upgrade" (+ I added "actions"); Maor said that customers don't need to coordinate platform shutdowns. 
    {{< /internal-release-note >}}

